### ISSUE TITLE
Beam stops allowing touch feedback

### ISSUE THREAD

**Issue by markseltenrijch** [awkward/beam#13]
Creating an issue is easy! Here are some steps to help you:

## User feedback

Beam stops allowing touch feedback. Cannot click, go back, upvote, etc. until I close the app and reopen. Happens very often since new app update 2.6.1

## Device information

Device model: iPhone X
iOS version: 11.2.2
App version: 2.6.1
Compiled the app yourself: No

**Comment by robinspeijer** [comment]
In 2.7, we've made some changes that might fix this issue. 

If this happens again, we'd need some additional info like:
- a video that demonstrates the problem
- a sysdiagnose file from the moment that the app does not allow touch feedback anymore:  https://download.developer.apple.com/iOS/iOS_Logs/sysdiagnose_Logging_Instructions.pdf
