### ISSUE TITLE
Swift Compiler Error - Missing Classes

### ISSUE THREAD

**Issue by ajfigueroa** [awkward/beam#16]
## User feedback
On the latest master, the following classes are missing from the project causing a Swift compilation error:
- `ProfileViewController.swift`
- `CurrentUserProfileViewController.swift`
- `ProfileSwitchButton.swift`

Am I missing something in the setup process?

## Device information

Xcode 9.4.1

### Warning
<img width="1135" alt="screen shot 2018-07-30 at 12 14 04 am" src="https://user-images.githubusercontent.com/3321592/43377224-9a742408-938d-11e8-8287-95622864b256.png">

### Files greyed out
<img width="1459" alt="screen shot 2018-07-30 at 12 14 35 am" src="https://user-images.githubusercontent.com/3321592/43377226-9b97ab66-938d-11e8-8254-5db49e53e535.png">

**Comment by renssies** [comment]
Sorry that it took me a while to respond, turns out we were using an old gitignore file that was set to exclude the "profile" folder. It should be fixed on master now!
