### ISSUE TITLE
Development moved to PowerMobileTeam/beam?

### ISSUE THREAD

**Issue by halleygen** [awkward/beam#17]
I love this app and am hoping to contribute to it when I get some free time. This morning when I checked the trending swift repos on GitHub I saw that there is now [this repo](https://github.com/PowerMobileTeam/beam), which is newer than this one.

Should I submit my changes there? Has Awkward sold beam?

Thanks

**Comment by renssies** [comment]
No we have not sold, looks like someone just copied the repo and edited a few pieces of text. 

Even in the description they only changed the company name
