### ISSUE TITLE
Bug - Enabling system dark mode while using default theme causes some areas to appear dark

### ISSUE THREAD

**Issue by tommyle** [awkward/beam#20]
## User feedback

If you enable dark mode on your phone but use light mode in Beam, some areas of the app will appear dark.

## Reproduction steps

1. Enable dark mode in iOS
2. Enable light mode in Beam
3. Some areas of the Beam app appear in dark mode

## Device information

Device model: iPhone X
iOS version: 13.1.2
App version: 2.6.1
Compiled the app yourself: Yes

## Screenshot/video

<img src="https://user-images.githubusercontent.com/656538/68968221-0c497280-07b0-11ea-970b-2858751afdc3.PNG" height="500">
<img src="https://user-images.githubusercontent.com/656538/68968222-0c497280-07b0-11ea-91f7-c8c4b752c651.PNG" height="500">

**Comment by robinspeijer** [comment]
Your PR #22 has been merged to master and should be available in the next Beam update.
