### ISSUE TITLE
Add visual indication for stickied comments

### ISSUE THREAD

**Issue by markseltenrijch** [awkward/beam#5]
Beam supports stickied comments, but it doesn't visually indicate that it's a stickied comment. We'd like to implement the same visual as for stickied posts.

**Comment by tommyle** [comment]
@markseltenrijch This should be marked as complete, its working in the latest version 2.6.1
![IMG_A8CC96F2665D-1](https://user-images.githubusercontent.com/656538/68920484-59dbc600-0743-11ea-996e-99ba48c4d1d5.jpeg)
