### ISSUE TITLE
Don't have rights to recursive submodules

### ISSUE THREAD

**Issue by thesecondfocusspan** [awkward/beam#6]
## User feedback
The command to recursive submodules failed: git submodule update --init --recursive
Am I missing something?

## Device information

Device model: macOS 10.13

## Screenshot/video (optional)
![subclone](https://user-images.githubusercontent.com/14815415/33694725-381eed52-db2c-11e7-9d5c-3e566d7e972b.png)

**Comment by renssies** [comment]
I tried to reproduce the issue on a new account on my MacBook, but I'm not running into any permission issues. 

Have you used the `git` commando before in your terminal?

**Comment by renssies** [comment]
Also make sure you've done the following:
- Have a SSH key in your github account: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/
- Setup a git username (`git config --global user.name "USERNAME"`)
- Setup a git email (`git config --global user.email "EMAIL"`)

**Comment by thesecondfocusspan** [comment]
You are right! The git command confused with my gitlab setting. I fix my setting and it can clone recursive.
