### ISSUE TITLE
Bug - App becomes a complete black screen exiting app's modal style pop-up menus

### ISSUE THREAD

**Issue by ZestMyu** [awkward/beam#8]
## User feedback

Upon navigating to ‘profile’ > ‘settings (gear on top right)’, the app background goes completely black. Exiting the settings will cause the previous screen to appear for a split second before going all black again. At this point I’m unable to use the app until after I force close it.

Edit 1: The same seems to occur when I swipe right on a comment to reply. Both actions result in 'beam' launching the app's own modal style pop-up menu.

Troubleshooting: Reboot of device does not prevent this from happening.

## Device information

Device model: iPad Mini 4
iOS version: 11.2.1 (15C153)
App version: 2.6 (384)
Compiled the app yourself: No

## Screenshot/video (optional)

**Comment by renssies** [comment]
I was able to fix this bug. Version 2.6.1 will be submitted soon to address this :)
