### ISSUE TITLE
"Unixporn" search keyword is blocked due to it containing "porn"

### ISSUE THREAD

**Issue by an0sunshy** [awkward/beam#9]
Creating an issue is easy! Here are some steps to help you:

## User feedback
Keyword "unixporn" should be whiteisted

## Device information

Device model: iPhone 7 Plus
iOS version: iOS 11.2.2
App version: v2.6
Compiled the app yourself: No

## Screenshot/video (optional)
![img_1593](https://user-images.githubusercontent.com/6316102/34999565-09c5f272-fab0-11e7-9426-27f93f22a435.PNG)

**Comment by renssies** [comment]
Thanks, I've added this word to the whitelist on the server. I've also closed you PR because the words in the code are only loaded if the server can never be found.

**Comment by an0sunshy** [comment]
Thanks!
